#!/bin/bash

# Demander à l'utilisateur les informations de connexion
read -p "Adresse du broker MQTT : " broker_address
read -p "Port : " port
read -p "Nom d'utilisateur (laissez vide si non utilisé) : " username
read -sp "Mot de passe (laissez vide si non utilisé) : " password
echo

# Demander le sujet et le message à publier
read -p "Sujet : " topic
read -p "Message : " message

# Utiliser les informations pour publier un message
mosquitto_pub -h "$broker_address" -p "$port" -t "$topic" -m "$message" -u "$username" -P "$password"
