#!/bin/bash

# Demander le nom d'utilisateur
read -p "Nom d'utilisateur : " username

# Demander le mot de passe
read -sp "Mot de passe : " password
echo

# Ajouter l'utilisateur et le mot de passe au fichier d'authentification
mosquitto_passwd -b /etc/mosquitto/auth.txt $username $password

echo "Utilisateur ajouté avec succès."
